export const clerkAppearance = {
  variables: {
    colorPrimary: '#151515',
    colorPrimaryForeground: '#fffefa',
    colorDanger: '#b94a48',
    colorSuccess: '#2f6f52',
    colorNeutral: '#151515',
    colorForeground: '#151515',
    colorMuted: '#eeede8',
    colorMutedForeground: '#707070',
    colorBackground: '#fffefa',
    colorInputForeground: '#151515',
    colorInput: '#fffefa',
    colorBorder: '#cbc7bd',
    colorRing: 'rgba(21, 21, 21, 0.18)',
    fontFamily: "'Mona Sans', ui-sans-serif, system-ui, sans-serif",
    fontFamilyButtons: "'Mona Sans', ui-sans-serif, system-ui, sans-serif",
    borderRadius: '14px',
    spacing: '1rem',
  },
  elements: {
    rootBox: 'w-full',
    cardBox: 'w-full max-w-[420px]',
    card: 'rounded-panel border border-line bg-surface shadow-panel',
    headerTitle: 'font-sans text-2xl font-semibold tracking-[-.05em] text-ink',
    headerSubtitle: 'text-sm text-muted',
    formFieldLabel: 'text-xs font-medium text-ink',
    formFieldInput: 'h-11 rounded-input border-line-strong bg-surface text-base text-ink',
    formButtonPrimary: 'rounded-control bg-ink text-white hover:bg-ink-strong',
    formButtonReset: 'rounded-control border border-line-strong bg-surface text-ink hover:bg-soft',
    socialButtonsBlockButton: 'rounded-input border-line-strong bg-surface text-ink hover:bg-soft',
    dividerText: 'text-xs text-muted',
    footerActionLink: 'text-ink underline-offset-4 hover:underline',
    footerPagesLink: 'text-muted underline-offset-4 hover:text-ink hover:underline',
  },
} as const
