import { themeColors } from '@/lib/theme'

export const clerkAppearance = {
  variables: {
    colorPrimary: themeColors.ink,
    colorPrimaryForeground: themeColors.surface,
    colorDanger: themeColors.danger,
    colorSuccess: themeColors.success,
    colorNeutral: themeColors.ink,
    colorForeground: themeColors.ink,
    colorMuted: themeColors.soft,
    colorMutedForeground: themeColors.muted,
    colorBackground: themeColors.surface,
    colorInputForeground: themeColors.ink,
    colorInput: themeColors.surface,
    colorBorder: themeColors.lineStrong,
    colorRing: themeColors.ring,
    fontFamily: "'Mona Sans', ui-sans-serif, system-ui, sans-serif",
    fontFamilyButtons: "'Mona Sans', ui-sans-serif, system-ui, sans-serif",
    borderRadius: '14px',
    spacing: '1rem',
  },
  elements: {
    rootBox: 'w-full',
    cardBox: 'w-full max-w-[420px]',
    card: 'rounded-panel border border-line bg-surface shadow-panel',
    headerTitle: 'font-sans text-2xl font-semibold tracking-[-.05em] text-ink',
    headerSubtitle: 'text-sm text-muted',
    formFieldLabel: 'text-xs font-medium text-ink',
    formFieldInput: 'h-11 rounded-input border-line-strong bg-surface text-base text-ink',
    formButtonPrimary: 'rounded-control bg-ink text-white hover:bg-ink-strong',
    formButtonReset: 'rounded-control border border-line-strong bg-surface text-ink hover:bg-soft',
    socialButtonsBlockButton: 'rounded-input border-line-strong bg-surface text-ink hover:bg-soft',
    dividerText: 'text-xs text-muted',
    footerActionLink: 'text-ink underline-offset-4 hover:underline',
    footerPagesLink: 'text-muted underline-offset-4 hover:text-ink hover:underline',
  },
} as const
