import { ArrowDown, ArrowUp, CalendarDots, CircleNotch, ClockCounterClockwise, X } from '@phosphor-icons/react'
import { fromKey } from '../allocation'
import { entryDate, formatShort } from '../lib/entry-utils'
import type { Entry } from '../types/entry'

export function ActivityList({ entries, deletingEntryId, onEdit, onRemove }: { entries: Entry[]; deletingEntryId: string | null; onEdit: (entry: Entry) => void; onRemove: (id: string) => void }) {
  const recentEntries = [...entries].sort((a, b) => b.occurredAt.localeCompare(a.occurredAt)).slice(0, 5)
  return <section className="activity-section"><div className="section-heading activity-heading"><div><p className="eyebrow">recent activity</p><h2>What moved.</h2></div><ClockCounterClockwise size={22} /></div><div className="activity-list">{recentEntries.length ? recentEntries.map(entry => <div className="activity-row" key={entry.id} onClick={() => onEdit(entry)} role="button" tabIndex={0} onKeyDown={event => event.key === 'Enter' && onEdit(entry)}><span className={`activity-icon ${entry.type}`}>{entry.type === 'income' ? <ArrowDown size={16} /> : <ArrowUp size={16} />}</span><span className="activity-name"><strong>{entry.title || entry.category || (entry.type === 'income' ? 'Income' : 'Expense')}</strong><small>{entry.category ?? 'Other'} · {fromKey(entryDate(entry)).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} · {entry.occurredAt.slice(11, 16)}</small></span><b className={entry.type === 'income' ? 'income-text' : ''}>{entry.type === 'income' ? '+' : '-'}{formatShort(entry.amount)}</b><button className="remove-entry" disabled={deletingEntryId === entry.id} onClick={event => { event.stopPropagation(); onRemove(entry.id) }} aria-label={`Remove ${entry.title || entry.category || entry.type}`}>{deletingEntryId === entry.id ? <CircleNotch className="loading-spinner" size={15} /> : <X size={15} />}</button></div>) : <div className="empty-activity"><CalendarDots size={22} /><p>Your first record will show up here.</p></div>}</div></section>
}
